---
- name: Ensure PGP key is installed
  apt_key: keyserver=keyserver.ubuntu.com
           id=561F9B9CAC40B2F7

- name: Ensure HTTPS support for APT is installed
  apt:
    name:
        - apt-transport-https
        - ca-certificates
    state: present

- name: Ensure the Passenger APT-repository is added
  apt_repository:
    repo: 'deb https://oss-binaries.phusionpassenger.com/apt/passenger xenial main'

- name: Install nginx-extras and Passenger
  apt:
    name:
        - nginx-extras
        - passenger
    state: present

- name: Add passenger.conf to nginx
  copy: src=passenger.conf dest=/etc/nginx/conf.d/passenger.conf
  notify: Restart nginx
