default_language_version:
    python: python3.7
repos:
  -   repo: https://github.com/pre-commit/mirrors-autopep8
      rev: ''  # Use the sha / tag you want to point at
      hooks:
      -   id: autopep8
