swagger: '2.0'
info:
  description: API for RestoWeb application
  version: 1.0.0
  title: RestoWeb
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: groep22.webdev.ilabt.imec.be
basePath: /
tags:
  - name: Restos
    description: Everything about Restos
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
  - name: Menus
    description: Managing resto menus
  - name: Dishes
    description: Managing individual dishes
schemes:
  - https
  - http
components:
  parameters:
    resto_id:  # <-- Arbitrary name for the definition that will be used to refer to it.
                  # Not necessarily the same as the parameter name.
      in: path
      name: resto_id
      required: true
      schema:
        type: integer
        minimum: 0
      description: The id of the resto to return
    dish_id:
      in: path
      name: dish_id
      required: true
      schema:
        type: integer
        minimum: 0
      description: The id of the dish to return
    menu_id:
      in: path
      name: menu_id
      required: true
      schema:
        type: integer
        minimum: 0
      description: The id of the menu to return
paths:
  /:
    get:
      produces:
        - html
        - json
      responses:
        '200':
          description: navigation information
  /restos:
    get:
      tags:
      - Restos
      produces:
        - html
        - json
      responses:
        '200':
          description: Gives a list of restos
     
    post:
      tags:
      - Restos
      produces:
        - json
      responses:
        '200':
          description: Resto successfully added
          
  '/restos/{resto_id}':
    parameters:
    - $ref: '#/components/parameters/resto_id'
      
    get:
      tags:
        - Restos
      produces:
        - html
        - json
      responses:
        '200':
          description: Gives details for a resto
    delete:
      tags:
        - Restos
      produces:
        - json
      responses:
        '200':
          description: Resto succesfully deleted
          
  /restos/{resto_id}/menus:
    parameters:
    - $ref: '#/components/parameters/resto_id'
    get:
      tags:
      - Restos
      description: Lists the menus of a certain resto
      produces:
      - html
      - json
      responses:
        200:
          description: gives the list of restos
    post:
      tags:
      - Restos
      description: Add a menu to a certain resto
      produces:
      - json
      responses:
        200:
          description: Menu added succesfully
    
  
    
    
  /dishes:
    get:
      tags:
        - Dishes
      produces:
        - html
        - json
      responses:
        '200':
          description: Shows all dishes
    post:
      tags:
        - Dishes
      produces:
        - json
      responses:
        200:
          description: Dish added succesfully
          
  '/dishes/{dish_id}':
    parameters:
    - $ref: '#/components/parameters/dish_id'
    get:
      tags:
        - Dishes
      produces:
        - html
        - json
      responses:
        '200':
          description: Gives details about a dish
    delete:
      tags:
        - Dishes
      produces:
        - json
      responses:
        200:
          description: Dish deleted succesfully
    put:
      tags:
        - Dishes
      produces:
        - json
      responses:
        200:
          description: Dish updated succesfully
 
  /menus:
    get:
      tags:
        - Menus
      produces:
        - html
        - json
      responses:
        '200':
          description: See all existing menus
    post:
      tags:
      - Menus
      produces:
      - json
      responses:
        200:
          description: Menu added succesfully
          
  '/menus/{menu_id}':
    parameters:
    - $ref: '#/components/parameters/menu_id'
    get:
      tags:
        - Menus
      produces:
        - html
        - json
      responses:
        '200':
          description: See details about a specific menu
  '/menus/{menu_id}/dishes':
    parameters:
    - $ref: '#/components/parameters/menu_id'
    get:
      tags:
      - Menus
      produces:
      - json
      responses:
        200:
          description: see all dishes in a specific menu
    post:
      tags:
        - Menus
      produces:
        - json
      responses:
        200:
          description: succesfully added dish to menu
        
    
securityDefinitions:
  petstore_auth:
    type: oauth2
    authorizationUrl: 'http://petstore.swagger.io/oauth/dialog'
    flow: implicit
    scopes:
      'write:pets': modify pets in your account
      'read:pets': read your pets
  api_key:
    type: apiKey
    name: api_key
    in: header
definitions:
  User:
    type: object
    properties:
      id:
        type: integer
        format: int64
      username:
        type: string
      password_hash:
        type: string
        format: password
    xml:
      name: User
  Resto:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      zip_code:
        type: string
      city:
        type: string
      address:
        type: string
      campus: 
        type: string
      description:
        type: string
    xml:
      name: Resto
  Schedule:
    type: object
    properties:
      id:
        type: integer
        format: int64
      time_open:
        type: string
        format: date-time
      time_closed:
        type: string
        format: date-time
      breakfast:
        type: boolean
        default: false
      lunch:
        type: boolean
        default: false
      dinner:
        type: boolean
        default: false
      resto_id:
        type: integer
        format: int64
    xml:
      name: Schedule
  Menu:
    type: object
    properties:
      id:
        type: integer
        format: int64
      date:
        type: string
        format: date
      resto_id:
        type: integer
        format: int64
    xml:
      name: Menu
  Dish:
    type: object
    properties:
      id: 
        type: integer
        format: int64
      name:
        type: string
      type:
        type: string
      price:
        type: number
      diet:
        type: string
      menu_id: 
        type: integer
        format: int64
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
