---
- name: Create user
  user:
    name: "{{ user_name }}"
    shell: "{{ user_shell }}"
  register: user

- name: Create directies
  file:
    path: "{{ user.home }}/{{ item.directory }}"
    mode: "{{ item.mode | default('0755')}}"
    owner: "{{ item.owner | default(user.name) }}"
    group: "{{ item.group | default(user.name) }}"
    state: directory
  with_items: "{{ user_directories }}"
