---
- name: Clone resto git repo
  git:
    repo: https://github.com/abeforgit/RestoWeb.git
    dest: /home/resto/RestoWeb
  become_user: resto

- name: software-properties-common
  apt:
    name: software-properties-common
    state: present

- name: Ensure the Python APT-repository is added
  apt_repository:
    repo: ppa:deadsnakes/ppa

- name: Install python3.7
  apt:
    name:
        - python3.7
        - python3.7-dev
        - python3.7-venv
    state: present

- name: Check out the frontend repo
  local_action:
    module: git
    repo: https://github.com/abeforgit/RestoWeb-Front
    dest: /tmp/restoweb-front
    version: development

- name: Install packages from Restoweb-Front
  local_action:
    module: yarn
    path: /tmp/restoweb-front

- name: Run yarn build
  local_action:
    module: shell
    _raw_params: "VUE_APP_API_URL='https://groep22.webdev.ilabt.imec.be' yarn run build"
    chdir: /tmp/restoweb-front


- name: Copy over dist folder
  copy:
    src: /tmp/restoweb-front/dist/
    dest: /home/resto/public/
    owner: www-data


- name: Setup restoweb software
  shell: /home/resto/RestoWeb/server/setup.sh
  args:
    chdir: /home/resto/RestoWeb/server
    executable: /bin/bash
  become_user: resto

- name: Install systemd unit file
  template:
      src: restoweb.service.j2
      dest: /etc/systemd/system/restoweb.service

- name: Copy over config file
  template:
      src: restoweb.conf.j2
      dest: /home/resto/restoweb.conf
      owner: resto

- name: Start restoweb
  systemd: state=restarted name=restoweb daemon_reload=yes
