"""empty message

Revision ID: 0ab4ec814b96
Revises: 4ef1fa4f00c2
Create Date: 2019-05-06 20:22:18.404026

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session
from restoweb.models import User, generate_api_token


# revision identifiers, used by Alembic.
revision = '0ab4ec814b96'
down_revision = '4ef1fa4f00c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apikey', sa.String(32), nullable=False, server_default="REPLACE_ME"))
    conn = op.get_bind()
    session = Session(bind=conn)
    for user in session.query(User).filter_by(apikey="REPLACE_ME"):
        user.apikey = generate_api_token()
        session.add(user)
    session.commit()

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('apikey')

    # ### end Alembic commands ###
