"""empty message

Revision ID: 0f80352a1bbb
Revises: 51e7e2283c7e
Create Date: 2019-03-18 16:37:08.362418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f80352a1bbb'
down_revision = '51e7e2283c7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('type', sa.String(length=30), nullable=False),
                    sa.Column('price', sa.Float(), nullable=True),
                    sa.Column('diet', sa.String(length=50), nullable=True),
                    sa.Column('menu_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.alter_column('menu', 'date',
                    existing_type=sa.DATE(),
                    nullable=False)
    op.alter_column('resto', 'address',
                    existing_type=sa.VARCHAR(length=50),
                    nullable=False)
    op.alter_column('resto', 'city',
                    existing_type=sa.VARCHAR(length=30),
                    nullable=False)
    op.alter_column('resto', 'zip_code',
                    existing_type=sa.VARCHAR(length=10),
                    nullable=False)
    op.add_column('schedules', sa.Column(
        'breakfast', sa.Boolean(), nullable=False))
    op.add_column('schedules', sa.Column(
        'dinner', sa.Boolean(), nullable=False))
    op.add_column('schedules', sa.Column(
        'lunch', sa.Boolean(), nullable=False))
    op.add_column('schedules', sa.Column(
        'time_closed', sa.Time(), nullable=False))
    op.alter_column('schedules', 'time_open',
                    existing_type=sa.TIME(),
                    nullable=False)
    op.drop_column('schedules', 'working_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column(
        'working_time', sa.INTEGER(), nullable=True))
    op.alter_column('schedules', 'time_open',
                    existing_type=sa.TIME(),
                    nullable=True)
    op.drop_column('schedules', 'time_closed')
    op.drop_column('schedules', 'lunch')
    op.drop_column('schedules', 'dinner')
    op.drop_column('schedules', 'breakfast')
    op.alter_column('resto', 'zip_code',
                    existing_type=sa.VARCHAR(length=10),
                    nullable=True)
    op.alter_column('resto', 'city',
                    existing_type=sa.VARCHAR(length=30),
                    nullable=True)
    op.alter_column('resto', 'address',
                    existing_type=sa.VARCHAR(length=50),
                    nullable=True)
    op.alter_column('menu', 'date',
                    existing_type=sa.DATE(),
                    nullable=True)
    op.drop_table('product')
    # ### end Alembic commands ###
