"""empty message

Revision ID: 27891fde3e02
Revises: a2c0922e527a
Create Date: 2019-05-20 00:46:28.795662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27891fde3e02'
down_revision = 'a2c0922e527a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favourite_resto', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'resto', ['favourite_resto'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('favourite_resto')

    # ### end Alembic commands ###
