"""empty message

Revision ID: 51e7e2283c7e
Revises: 
Create Date: 2019-03-15 16:36:05.696453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51e7e2283c7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    resto_table = op.create_table('resto',
                                  sa.Column('id', sa.Integer(),
                                            nullable=False),
                                  sa.Column('name', sa.String(
                                      length=50), nullable=False),
                                  sa.Column('zip_code', sa.String(
                                      length=10), nullable=True),
                                  sa.Column('city', sa.String(
                                      length=30), nullable=True),
                                  sa.Column('address', sa.String(
                                      length=50), nullable=True),
                                  sa.Column('campus', sa.String(
                                      length=50), nullable=True),
                                  sa.Column('description', sa.Text(),
                                            nullable=True),
                                  sa.PrimaryKeyConstraint('id')
                                  )
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(
                        length=50), nullable=False),
                    sa.Column('password_hash', sa.String(
                        length=120), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('menu',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('date', sa.Date(), nullable=True),
                    sa.Column('resto_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['resto_id'], ['resto.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('schedules',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('time_open', sa.Time(), nullable=True),
                    sa.Column('working_time', sa.Integer(), nullable=True),
                    sa.Column('resto_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['resto_id'], ['resto.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedules')
    op.drop_table('menu')
    op.drop_table('user')
    op.drop_table('resto')
    # ### end Alembic commands ###
