"""empty message

Revision ID: bcf0852a5ec6
Revises: 
Create Date: 2019-03-18 16:56:51.721286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcf0852a5ec6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resto',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('zip_code', sa.String(
                        length=10), nullable=False),
                    sa.Column('city', sa.String(length=30), nullable=False),
                    sa.Column('address', sa.String(length=50), nullable=False),
                    sa.Column('campus', sa.String(length=50), nullable=True),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(
                        length=50), nullable=False),
                    sa.Column('password_hash', sa.String(
                        length=120), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('menu',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('date', sa.Date(), nullable=False),
                    sa.Column('resto_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['resto_id'], ['resto.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('schedules',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('time_open', sa.Time(), nullable=False),
                    sa.Column('time_closed', sa.Time(), nullable=False),
                    sa.Column('breakfast', sa.Boolean(), nullable=False),
                    sa.Column('lunch', sa.Boolean(), nullable=False),
                    sa.Column('dinner', sa.Boolean(), nullable=False),
                    sa.Column('resto_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['resto_id'], ['resto.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('product',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('type', sa.String(length=30), nullable=False),
                    sa.Column('price', sa.Float(), nullable=True),
                    sa.Column('diet', sa.String(length=50), nullable=True),
                    sa.Column('menu_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    op.drop_table('schedules')
    op.drop_table('menu')
    op.drop_table('user')
    op.drop_table('resto')
    # ### end Alembic commands ###
