"""empty message

Revision ID: d74c0351ba54
Revises: a2c0922e527a
Create Date: 2019-05-20 01:36:11.037036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd74c0351ba54'
down_revision = 'a2c0922e527a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favourite_resto_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('geef_het_kindje_een_naam', 'resto', ['favourite_resto_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('favourite_resto_id')

    # ### end Alembic commands ###
