"""empty message

Revision ID: e7a35d7df82e
Revises: bcf0852a5ec6
Create Date: 2019-04-25 17:08:43.017162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7a35d7df82e'
down_revision = 'bcf0852a5ec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dish',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('diet', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_open', sa.Time(), nullable=False),
    sa.Column('time_closed', sa.Time(), nullable=False),
    sa.Column('resto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resto_id'], ['resto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu_contains_dish',
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dish.id'], ),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ),
    sa.PrimaryKeyConstraint('menu_id', 'dish_id')
    )
    op.drop_table('product')
    op.drop_table('schedules')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedules',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('time_open', sa.TIME(), nullable=False),
    sa.Column('time_closed', sa.TIME(), nullable=False),
    sa.Column('breakfast', sa.BOOLEAN(), nullable=False),
    sa.Column('lunch', sa.BOOLEAN(), nullable=False),
    sa.Column('dinner', sa.BOOLEAN(), nullable=False),
    sa.Column('resto_id', sa.INTEGER(), nullable=True),
    sa.CheckConstraint('breakfast IN (0, 1)'),
    sa.CheckConstraint('dinner IN (0, 1)'),
    sa.CheckConstraint('lunch IN (0, 1)'),
    sa.ForeignKeyConstraint(['resto_id'], ['resto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('type', sa.VARCHAR(length=30), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.Column('diet', sa.VARCHAR(length=50), nullable=True),
    sa.Column('menu_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('menu_contains_dish')
    op.drop_table('schedule')
    op.drop_table('dish')
    # ### end Alembic commands ###
